development:
  adapter: async

test:
  adapter: async

sandbox:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6380/1" } %>
  channel_prefix: api_sandbox

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6380/1" } %>
  channel_prefix: api_production
